### ISSUE TITLE
Error Creating Invoice

### ISSUE THREAD

**Issue by cwoolum** [ruckus/quickeebooks#55]
Hi Guys,

When I am creating an invoice, I get the error

undefined method `to_xml' for 2:Fixnum

Here is my stack trace

 (gem) roxml-3.3.1/lib/roxml/xml/references.rb:301:in `block (2 levels) in update_xml'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:300:in`tap'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:300:in `block in update_xml'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:291:in`tap'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:291:in `update_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:63:in`block (2 levels) in to_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:60:in `each'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:60:in`block in to_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:52:in `tap'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:52:in`to_xml'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:298:in `block in update_xml'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:291:in`tap'
  (gem) roxml-3.3.1/lib/roxml/xml/references.rb:291:in `update_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:63:in`block (2 levels) in to_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:60:in `each'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:60:in`block in to_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:52:in `tap'
  (gem) quickeebooks-0.1.5/lib/quickeebooks.rb:52:in`to_xml'
  (gem) quickeebooks-0.1.5/lib/quickeebooks/online/model/intuit_type.rb:32:in `to_xml_inject_ns'
  (gem) quickeebooks-0.1.5/lib/quickeebooks/common/online_line_item_model_methods.rb:18:in`to_xml_ns'
  (gem) quickeebooks-0.1.5/lib/quickeebooks/online/service/invoice.rb:14:in `create'
  app/services/quickbooks_sync.rb:82:in`block (2 levels) in export_invoices'
  (gem) activerecord-3.2.11/lib/active_record/relation/delegation.rb:6:in `each'
  (gem) activerecord-3.2.11/lib/active_record/relation/delegation.rb:6:in`each'
  app/services/quickbooks_sync.rb:59:in `block in export_invoices'
  (gem) activerecord-3.2.11/lib/active_record/associations/collection_proxy.rb:89:in`each'
  (gem) activerecord-3.2.11/lib/active_record/associations/collection_proxy.rb:89:in `method_missing'
  app/services/quickbooks_sync.rb:58:in`export_invoices'
  app/controllers/quickbook_controller.rb:50:in `block in sync_invoices'
  (gem) actionpack-3.2.11/lib/action_controller/metal/mime_responds.rb:270:in`call'
  (gem) actionpack-3.2.11/lib/action_controller/metal/mime_responds.rb:270:in `retrieve_collector_from_mimes'
  (gem) actionpack-3.2.11/lib/action_controller/metal/mime_responds.rb:194:in`respond_to'
  app/controllers/quickbook_controller.rb:49:in `sync_invoices'
  (gem) actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  (gem) actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in`process_action'
  (gem) actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:447:in`_run__926487399__process_action__932969398__callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
  (gem) actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in`process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in instrument'
  (gem) activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `instrument'
  (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  (gem) activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:34:in `block in process_action'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:268:in`block in perform_action_with_newrelic_trace'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:263:in`perform_action_with_newrelic_trace'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:33:in `process_action'
  (gem) actionpack-3.2.11/lib/abstract_controller/base.rb:121:in`process'
  (gem) actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `process'
  (gem) actionpack-3.2.11/lib/action_controller/metal.rb:203:in`dispatch'
  (gem) actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  (gem) actionpack-3.2.11/lib/action_controller/metal.rb:246:in`block in action'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/mapper.rb:42:in`call'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in`each'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in`call'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/rack/error_collector.rb:8:in `call'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/rack/agent_hooks.rb:14:in`call'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/rack/browser_monitoring.rb:12:in `call'
  (gem) newrelic_rpm-3.5.8.72/lib/new_relic/rack/developer_mode.rb:24:in`call'
  (gem) better_errors-0.3.2/lib/better_errors/middleware.rb:51:in `app_call'
  (gem) better_errors-0.3.2/lib/better_errors/middleware.rb:45:in`call'
  (gem) bullet-4.3.1/lib/bullet/rack.rb:11:in `call'
  (gem) warden-1.2.1/lib/warden/manager.rb:35:in`block in call'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in `catch'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in`call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  (gem) rack-1.4.5/lib/rack/etag.rb:23:in`call'
  (gem) rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in`call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in`call'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:205:in`call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  (gem) activerecord-3.2.11/lib/active_record/query_cache.rb:64:in`call'
  (gem) activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__660557959__call__829375442__callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in`__run_callback'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in`run_callbacks'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  (gem) rails-dev-tweaks-0.6.1/lib/rails_dev_tweaks/granular_autoload/middleware.rb:34:in`call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  (gem) airbrake-3.1.8/lib/airbrake/rails/middleware.rb:15:in`call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:18:in`call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  (gem) rack-1.4.5/lib/rack/methodoverride.rb:21:in`call'
  (gem) rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  (gem) activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  (gem) rack-1.4.5/lib/rack/lock.rb:15:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in`call'
  (gem) airbrake-3.1.8/lib/airbrake/user_informer.rb:16:in `_call'
  (gem) airbrake-3.1.8/lib/airbrake/user_informer.rb:12:in`call'
  (gem) railties-3.2.11/lib/rails/engine.rb:479:in `call'
  (gem) railties-3.2.11/lib/rails/application.rb:223:in`call'
  (gem) rack-1.4.5/lib/rack/content_length.rb:14:in `call'
  (gem) railties-3.2.11/lib/rails/rack/log_tailer.rb:17:in`call'
  (gem) thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
  (gem) thin-1.5.0/lib/thin/connection.rb:79:in`catch'
  (gem) thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
  (gem) thin-1.5.0/lib/thin/connection.rb:54:in`process'
  (gem) thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
  (gem) eventmachine-1.0.1/lib/eventmachine.rb:187:in`run_machine'
  (gem) eventmachine-1.0.1/lib/eventmachine.rb:187:in `run'
  (gem) thin-1.5.0/lib/thin/backends/base.rb:63:in`start'
  (gem) thin-1.5.0/lib/thin/server.rb:159:in `start'
  (gem) rack-1.4.5/lib/rack/handler/thin.rb:13:in`run'
  (gem) rack-1.4.5/lib/rack/server.rb:268:in `start'
  (gem) railties-3.2.11/lib/rails/commands/server.rb:70:in`start'
  (gem) railties-3.2.11/lib/rails/commands.rb:55:in `block in <top (required)>'
  (gem) railties-3.2.11/lib/rails/commands.rb:50:in`tap'
  (gem) railties-3.2.11/lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in`require'
  script/rails:6:in `<main>'

Here is my object inspected
# <Quickeebooks::Online::Model::Invoice:0x11a9c2b4 @line_items=[#<Quickeebooks::Online::Model::InvoiceLineItem:0x11e860dc @desc="Gildan 2000 - White", @amount=#<BigD

ecimal:11e8608c,'0.1E1',9(18)>, @unit_price=#<BigDecimal:118274ac,'0.44E1',18(18)>, @taxable=true, @quantity=20>, #<Quickeebooks::Online::Model::InvoiceLineItem:0x1
1827420 @desc="Gildan 2000 - White", @amount=#<BigDecimal:118273d0,'0.1E1',9(18)>, @unit_price=#<BigDecimal:11827394,'0.44E1',18(18)>, @taxable=true, @quantity=82>,
 #<Quickeebooks::Online::Model::InvoiceLineItem:0x11827308 @desc="Gildan 2000 - White", @amount=#<BigDecimal:118272b8,'0.1E1',9(18)>, @unit_price=#<BigDecimal:11827
27c,'0.44E1',18(18)>, @taxable=true, @quantity=10>, #<Quickeebooks::Online::Model::InvoiceLineItem:0x118271f0 @desc="Gildan 2000 - White", @amount=#<BigDecimal:1182
71a0,'0.1E1',9(18)>, @unit_price=#<BigDecimal:11827164,'-0.5E1',9(18)>, @taxable=true, @quantity=1>], @header=#<Quickeebooks::Online::Model::InvoiceHeader:0x11a9c27
8 @customer_id=2, @tax_rate=#<BigDecimal:11a9c228,'0.8E1',9(18)>, @total_amount=#<BigDecimal:11e88148,'0.52682E3',18(36)>, @sub_total_amount=#<BigDecimal:11e86e88,'
0.4878E3',18(36)>>>

What am I doing wrong??

**Comment by cwoolum** [comment]
Here is my code

``` ruby
  def export_invoices(account, oauth_client)
    sync = QuickbooksSync.new(account.quickbooks_token, account.quickbooks_secret)
    account.customers.each do |c|
      c.orders.has_line_items.each do |o|
        invoice_service = Quickeebooks::Online::Service::Invoice.new
        invoice_service.access_token = sync.oauth_client
        invoice_service.realm_id = account.quickbooks_realm_id

        invoice = Quickeebooks::Online::Model::Invoice.new
        header = Quickeebooks::Online::Model::InvoiceHeader.new
        header.customer_id=c.quickbooks_id
        header.tax_rate=o.sales_tax
        header.total_amount=o.order_total
        header.sub_total_amount=o.order_subtotal

        invoice.header= header
        o.lineitems.each do |li|
          lineitem = Quickeebooks::Online::Model::InvoiceLineItem.new
          lineitem.desc=li.description2
          lineitem.amount=li.price_per
          lineitem.unit_price=li.unit_cost2
          lineitem.taxable=li.taxable
          lineitem.quantity=li.amount2
          invoice.line_items << lineitem
        end
        puts invoice.inspect
        invoice_service.create(invoice)
      end
    end
  end
```

**Comment by cwoolum** [comment]
I dug a little deeper and the actual error seems to be when it tries to set customer Id = 2

**Comment by cwoolum** [comment]
Nevermind, this is my own fault. I was making customer id an integer and not the type of Quickeebooks::Online::Model::Id
